# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

array[:, 2] = 1
print("Modified array:")
print(array)

Original array:
[[19 15  2  9 19]
 [ 5 12 12  2 20]
 [ 3  9 15 14 10]
 [ 6 12 18  8 18]
 [11 17  8  3  7]]
Modified array:
[[19 15  1  9 19]
 [ 5 12  1  2 20]
 [ 3  9  1 14 10]
 [ 6 12  1  8 18]
 [11 17  1  3  7]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)
np.fill_diagonal(array, 0)
print("Modified array:")
print(array)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [3]:
array = np.arange(1, 37).reshape((6, 6))
print("Original array:")
print(array)

sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [4]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[ 3  7  5  8 13]
 [15 18  3  3 20]
 [11 17 11  7 20]
 [18  7  2  3 15]
 [ 4 15 14  1 18]]
Border elements:
[ 3  7  5  8 13  4 15 14  1 18 15 11 18 20 20 15]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [5]:
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Array 1:
[[ 6  7  9  6]
 [ 2  9  7  6]
 [ 9 10 10  3]]
Array 2:
[[ 4 10  2 10]
 [ 6  7  3  4]
 [10  9  4  9]]
Element-wise addition:
[[10 17 11 16]
 [ 8 16 10 10]
 [19 19 14 12]]
Element-wise subtraction:
[[ 2 -3  7 -4]
 [-4  2  4  2]
 [-1  1  6 -6]]
Element-wise multiplication:
[[24 70 18 60]
 [12 63 21 24]
 [90 90 40 27]]
Element-wise division:
[[1.5        0.7        4.5        0.6       ]
 [0.33333333 1.28571429 2.33333333 1.5       ]
 [0.9        1.11111111 2.5        0.33333333]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)
print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [6]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Original array:
[[14  7 15  5  4]
 [14  8  5  5  5]
 [12  8  4 12 13]
 [17 13  5 15  1]
 [ 4 19 14  2  6]]
Mean: 9.08
Median: 8.0
Standard Deviation: 5.074800488689186
Variance: 25.753600000000002


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [7]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [9]:
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[2 9 9]
 [2 9 1]
 [4 6 8]]
1D array:
[ 8  9 10]
Resulting array:
[[10 18 19]
 [10 18 11]
 [12 15 18]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [8]:
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[ 3  3 10  8]
 [ 8  5 10  8]
 [ 2  5  1  2]
 [ 9  2 10  9]]
1D array:
[ 7  7  9 10]
Resulting array:
[[-4 -4  3  1]
 [ 1 -2  3  1]
 [-7 -4 -8 -7]
 [-1 -8  0 -1]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [10]:
# Create a NumPy array of shape (3, 3) representing a matrix
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Original matrix:
[[ 7  5  6]
 [ 7  5  1]
 [ 4 10  5]]
Determinant: 249.9999999999999
Inverse:
[[ 0.06   0.14  -0.1  ]
 [-0.124  0.044  0.14 ]
 [ 0.2   -0.2   -0.   ]]
Eigenvalues: [16.34507051+0.j         0.32746474+3.8971654j  0.32746474-3.8971654j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [ ]:
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [11]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [12]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[ 9  5  8  1  1]
 [ 6  4 14 18 10]
 [15 13 11 20 16]
 [ 2 11 14 17 14]
 [ 7  4  9 17  8]]
Flattened array:
[ 9  5  8  1  1  6  4 14 18 10 15 13 11 20 16  2 11 14 17 14  7  4  9 17
  8]
Reshaped array:
[[ 9  5  8  1  1]
 [ 6  4 14 18 10]
 [15 13 11 20 16]
 [ 2 11 14 17 14]
 [ 7  4  9 17  8]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [ ]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [13]:
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[13  3  1 16]
 [ 3  1 18  1]
 [18 16  7  4]
 [ 6 16  4 11]]
Modified array:
[[10  3  1 10]
 [ 3  1 10  1]
 [10 10  7  4]
 [ 6 10  4 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [14]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [15]:
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [16]:
import numpy.ma as ma
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[ 8 12 14 18]
 [19 18 18 18]
 [ 9 17  8 13]
 [15 12 11 20]]
Masked array:
[[8 -- -- --]
 [-- -- -- --]
 [9 -- 8 --]
 [-- -- -- --]]
Sum of unmasked elements: 25


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [18]:
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[14  9 12]
 [14 13 13]
 [ 9  5  3]]
Masked array:
[[-- 9 12]
 [14 -- 13]
 [9 5 --]]
Modified masked array:
[[10  9 12]
 [14 10 13]
 [ 9  5 10]]
